/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: ur2R7u53dTipBxgsve4o7K

import { createUseGlobalVariants } from "@plasmicapp/react-web";

import { useScreenVariants as useScreenVariantsm8X0J1JmjKu } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: _m8X0J1jmjKu/globalVariant

export const _useGlobalVariants = createUseGlobalVariants({
  screen: useScreenVariantsm8X0J1JmjKu
});
